### ISSUE TITLE
Genome class / Breeding and Innovation numbers

### ISSUE THREAD

**Issue by strangedev** [strangedev/NEAT_PyGenetics#11]
Problem:

When following the program flow, there has to be a main class which ties all three graph representations together, in order to be able to access all the required methods and information at the right time.

Analysis of the situation:

For most steps, like clustering, breeding, selecting and mutating, the graph has to be examined in order to pick a spot for mutations to happen, compare two genomes, etc.
The AnalysisStructure (AnalysisGenome) is the most appropriate class for these operations, because of the intuitive graph representation (adjacency list).

The simulation structure is only needed for a single step, which is computing the output of the NN.
The storage structure is also only needed when storing the genomes in persistent storage.
(The storage structure could potentially handle innovation numbers / ids, but it shouldn't)

Original proposal:

The Simulation structure should be the main structure tying together all three different data structures. 

Objection:

However, the SimulationStructure (SimulationGenome), does not store information on genes (edges) but on neurons (nodes), which makes the analysis structure unfit for performing breeding/mutation/analysis. This is not a design flaw, because simulation structure ought to be a specialized class, only carrying the information it needs.
The simulation structure is therefore unfit for the purpose of  being our main data structure and should only be used for computation of the NN.

New proposal:

The analysis structure could potentially carry all of the needed information, but should remain a specialized class and not take the role of the main, combining class for the three structures for design purposes.
Instead, we should wrap the three structures into a Genome class, which will perform graph operations using the analysis structure and create the simulation- and storage structure lazily as needed, because either of them will either lose information or computational fitness once converted.

This will also clear out responsibility issues and make the program design more structured.

**Comment by yeldiRium** [comment]
My original thought was to use the StorageStructure as the Base class, because it can be persisted and loaded, thus providing an entry point. Because of this, we **need** to have the possibility to create Analysis- and SimulationStructures from StorageStructures.
Creating the SimulationStructure from the AnalysisStructure could provide difficult, thus we would have to load the StorageStructure every time we want to create the SimulationStructure or we'd have to keep the StorageStructure in memory.
Since all Analysis is mostly done all at once, the AnalysisStructure is - as you say - the most needed one (because Analysis is a lot to do), but we don't have to load it often. Most of the time we load a Genome, create the AnalysisStructure, perform Analysis, apply findings to the genome, then simulate it and store it again with the new information. Also the Analysis happens outside of the main director, so for the director it is best to use the structure that can best be used to create other structures.
Thus my approach would be to create constructors for the Analysis- and SimulationStructure, which take a StorageStructure as parameter and build themselves off of it. This is used to instantiate the needed Structure on the fly when initializing a Analysis-Action or a Simulation-Action.
The mainly used Structure in between and in the main directing class would thus be the StorageStructure.
Another argument in favor of the StorageStructure as the main structure is that it is best suited for mutation and breeding.

**Comment by yeldiRium** [comment]
Also imho no Genome Structure should contain references to other structural representations of itself.
The structure classes are made only for their specified purposes, they should not contain logic regarding the program flow or regarding the access of the different representations of a genome.
