### ISSUE TITLE
StorageStructure for Genomes

### ISSUE THREAD

**Issue by yeldiRium** [strangedev/NEAT_PyGenetics#2]
We need a dedicated structure for storing genomes.
This structure should be storage efficient and easy to use for mutation and breeding.

The current concept is to use a list/set of Genes, while these Genes are unique, stored in a seperate repository and referenced via id. (Flyweight pattern)
Genes basically are graph edges; they contain a head, a tail and an innovation value. Additional Gene information that is needed in the Genome is stored there, in combination with the gene id.

**Comment by strangedev** [comment]
Update:

Innovation numbers, which act as historical markers for tracing gene origin and allow us to compare genomes will be merged with the id numbers.

Rationale:
Id numbers, as well as innovation numbers, have to be unique in order to serve their purpose.
Both are assigned with increasing values and never changed once assigned. Merging the two properties means less memory use and less complicated code.

**Comment by yeldiRium** [comment]
I suggest dropping the Label of Genes and Genomes aswell (if that idea hasn't been dropped yet) and replacing it with the id. So there are no more strs roaming around, just plain ints.

**Comment by yeldiRium** [comment]
Update:

The StorageStructure also contains an optional AnalysisResult object (see #4). This object is added after the Genome was analyzed.
Since a genome does not change after it is created, Analysis has to be done once and the result won't change. Thus we want to persist the result of said Analysis.

**Comment by yeldiRium** [comment]
The StorageGenome should also contain a boolean flag `is_alive` and a `cluster_id`. The cluster_id already exists, the flag that says, if the genome belongs to the active population is currently named `dead`. This will be fixed in a push around sunday.

**Comment by strangedev** [comment]
Class implemented, now waiting for debugging.
